name: Daily Commit

on:
  schedule:
    - cron: '30 12 * * *'  # Runs at 12:30 UTC every day

jobs:
  create-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create daily commit (22f3001307@ds.study.iitm.ac.in)
        run: |
          echo "Daily update $(date)" >> daily-update.txt
          git add daily-update.txt
          git commit -m "Daily commit"
          git push
